import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const spaceGroteskRegular = Space_Grotesk({ subsets: ['latin'], weight: "400"});
const spaceGroteskMedium = Space_Grotesk({ subsets: ['latin'], weight: "500"});
const spaceGroteskBold = Space_Grotesk({ subsets: ['latin'], weight: "700"});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
